### ISSUE TITLE
On a Designs Likes Page, remove the word “By” from the usernames #110

### ISSUE THREAD

**Issue by wunmi-design** [Myoats/preprod#27]
![image](https://user-images.githubusercontent.com/37152320/38463174-8363e20e-3ac2-11e8-935b-4acd67542aac.png)

**Comment by penglididiom** [comment]
it has been fixed already

**Comment by wunmi-design** [comment]
I still see it:
https://www.myoats.com/wholikes.aspx?wd=602435

**Comment by penglididiom** [comment]
fixed
